apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: massdriver-backstage
  description: Local dev host for the Massdriver Backstage plugin.
  annotations:
    github.com/project-slug: massdriver-cloud/massdriver-backstage
spec:
  type: website
  owner: guests
  lifecycle: experimental
